# Generated by Django 5.0.3 on 2024-03-19 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
