# Generated by Django 5.0.3 on 2024-03-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_events_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
