# Generated by Django 5.0.3 on 2024-03-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_events_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.TextField(blank=True),
        ),
    ]
