# Generated by Django 5.0.3 on 2024-03-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_chatmsg'),
        ('user', '0017_alter_profile_profileimg'),
    ]

    operations = [
    ]
